FROM openjdk:8
WORKDIR /
ADD tomcat-6.0.5-jar-with-dependencies.jar tomcat-6.0.5-jar-with-dependencies.jar
ADD webapps/ webapps/
ADD conf/ conf/
EXPOSE 8081
CMD java -jar tomcat-6.0.5-jar-with-dependencies.jar
